name: deploy frontend application
on: 
  push:
    branches:
      - test

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: prepare the docker-compose run
        run : |
          ls

      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          
        
      - 
        name : prepare the docker-compose run
        run: |
          mkdir 234-deploylab-frontend
         
